### ISSUE TITLE
API not connecting to database

### ISSUE THREAD

**Issue by TheCatTree** [nealhartley/leashed#4]
containers are talking but I get this fault:
`Caught random exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnection.Open()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at leashApi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /src/leashApi/Startup.cs:line 79`

**Comment by TheCatTree** [comment]
looks like the api dose run it says ` Microsoft.Hosting.Lifetime[0]
 Now listening on: http://[::]:5000` but it never hits the database with network traffic

**Comment by TheCatTree** [comment]
Fixed, was dumb. Composer uses folder to make first part of container name. Mine was different.
Also need to start capturing dns look ups in containers for debug.
